depth_clustering:
  centerz_threshold: 0.5
  dis2d_max_threshold: 1.5
  dis2d_min_threshold: 1
  min_cluster_size: 150
  max_cluster_size: 1000
  smooth_window_size: 7
  ground_remove_angle_d: 10

lidar:
  is_mid360_custom_msg: false

odometry:
  is_use_odometry: false
  is_mid360_tf: true
  space_width: 5
  space_length: 18
  lidar2robot_x: 0.0
  lidar2robot_y: 0.24215

topic: 
  odom_topic: "/aft_mapped_to_init"
  lidar_topic: "/livox/lidar"


